import pickle
import numpy as np
import sys; sys.path.insert(0, '../../')
from methods.config import *
import matplotlib.pyplot as plt
import matplotlib as mpl
import scipy
import methods.sim_barcodes as sim


# freq_array = np.einsum('ij, i->ij', read_array, read_array.sum(axis=1)**-1.)
with open(f'{pickled_dir}/barcodes.pkl', 'rb') as f:
    barcodes = pickle.load(f)

with open(f'{pickled_dir}/vivo_array.pkl', 'rb') as f:
    vivo_array = pickle.load(f)

with open(f'{pickled_dir}/vivo_depths.pkl', 'rb') as f:
    vivo_depths = pickle.load(f)

with open(f'{pickled_dir}/vitro_array.pkl', 'rb') as f:
    vitro_array = pickle.load(f)

with open(f'{pickled_dir}/vitro_depths.pkl', 'rb') as f:
    vitro_depths = pickle.load(f)

with open(f'{pickled_dir}/reseq_array.pkl', 'rb') as f:
    reseq_array = pickle.load(f)

with open(f'{pickled_dir}/reseq_depths.pkl', 'rb') as f:
    reseq_depths = pickle.load(f)

with open(f'{pickled_dir}/timecourse_meta.pkl', 'rb') as f:
    library_meta = pickle.load(f)

with open(f'{pickled_dir}/library_array_map.pkl', 'rb') as f:
    library_array_map = pickle.load(f)

with open(f'{pickled_dir}/medium_to_well_map.pkl', 'rb') as f:
    medium_to_well_map = pickle.load(f)

with open(f'{pickled_dir}/well_to_medium_map.pkl', 'rb') as f:
    well_to_medium_map = pickle.load(f)

with open(f'{pickled_dir}/col_id_map.pkl', 'rb') as f:
    col_id_map = pickle.load(f)

reseq_depths[:, 1] = reseq_depths[:, 1] * 0.3

barcode_arrays = {'vivo': (vivo_array, vivo_depths),
                  'vitro': (vitro_array, vitro_depths),
                  'reseq': (reseq_array, reseq_depths)}

## generated by 0_barcode_processing.ipynb
with open(f'{pickled_dir}/barcode_pool_assignments.pkl', 'rb') as f:
    barcode_pool_assignments = pickle.load(f)

with open(f'{pickled_dir}/barcode_index_hopping_rates.pkl', 'rb') as f:
    barcode_hopping_rates = pickle.load(f)
### 

CEC_DAY = 100
SMALLINT_DAY = 200
def get_mouse_timecourse(expt, mouse, include_reseq=True, include_pseudo_derepped=True, 
                         min_depth=10**3, specific_timepoints=[], max_hopping_expectation=10**10):
    ##
    mouse_timepoints = []
    mouse_reads = []
    mouse_depths = [] ## effective depths

    for day in library_meta[expt][mouse]:
        if day in ['smallint', 'cecum'] and day not in specific_timepoints:
            continue

        day_replicates = []
        day_replicate_depths = []
        for (arr_name, arr_index) in library_meta[expt][mouse][day]:
            if arr_name != 'reseq' and not include_pseudo_derepped:
                continue
            if arr_name == 'reseq' and not include_reseq:
                continue

            
            read_array, read_depths = barcode_arrays[arr_name]
            lib_array, (lib_nominal_depth, lib_effective_depth) = read_array[arr_index], read_depths[arr_index]

            hopping_rate = barcode_hopping_rates[arr_name][arr_index]
            if hopping_rate*lib_nominal_depth > max_hopping_expectation:
                continue

            if np.sum(lib_array / lib_nominal_depth * lib_effective_depth) < min_depth:
                continue
            day_replicates.append( lib_array / lib_nominal_depth * lib_effective_depth)
            day_replicate_depths.append(lib_effective_depth)

    
        if len(day_replicates) == 0:
            continue
        summed_reads = np.sum(day_replicates, axis=0, dtype='float')
        summed_depth = np.sum(day_replicate_depths)
        if summed_depth < min_depth:
            continue
        
        # if day == 'smallint': # convert to integer day
        #     day = SMALLINT_DAY
        # if day == 'cecum':
        #     day = CEC_DAY
        mouse_timepoints.append(day)
        mouse_reads.append(summed_reads)
        mouse_depths.append(summed_depth)

    mouse_timepoints, mouse_reads, mouse_depths = mouse_timepoints, np.array(mouse_reads), np.array(mouse_depths)
    if np.any(specific_timepoints):
        # assert np.all([t in mouse_timepoints for t in specific_timepoints])
        timepoint_indices = [mouse_timepoints.index(t) for t in specific_timepoints]
        return specific_timepoints, mouse_reads[timepoint_indices], mouse_depths[timepoint_indices]
    else:
        return np.array(mouse_timepoints), mouse_reads, mouse_depths



def calc_freqs(read_array, depth_array=None):     
    if read_array.ndim > 1:
        if not np.any(depth_array):
            depth_array = np.sum(read_array, axis=1)

        return np.einsum('ij, i->ij', read_array, depth_array**-1.)
    else:
        if not np.any(depth_array):
            depth_array = np.sum(read_array)
        return read_array / depth_array


###


### BtVPI GENOME INFO
GENOME_LENGTH = 6260361

LE1 = 'GCCTTATAAATCTGGCTCTT'
LE2 = 'TGCTTCCGGCTTGGAAACCG'

CPS_LOCATIONS = {'cps1': (462368, 489867, +1), #start, stop, strand
                 'cps2': (573167, 595424, +1),
                 'cps3': (734869, 761399, +1),
                 'cps4': (1663708, 1685198, -1),
                 'cps5': (2032185, 2047991, -1),
                 'cps6': (2104512, 2124231, -1),
                 'cps7': (3580840, 3605962, -1),
                 'cps8': (32315, 71500, +1)}


### IN VITRO ASIDES

MONOSACCHARIDES = ['glucose', 'iron', 'fructose', 'galactose']
DISACCHARIDES = ['lactose', 'maltose', 'melibiose', 'sucrose', 'trehalose'] #['sucrose', 'maltose', 'trehalose', 'melibiose', ]
OLIGOSACCHARIDES = ['raffinose', 'stachyose']
POLYSACCHARIDES = ['avantafiber', 'bioecolians', 'bimuno', 'cravingzgone', 'fibersol',
                   'ISOT 160120', 'LC742', 'maltodextrin', 'prebiotin', 'precticx', 
                   'promitor', 'sunfiber', 'UMich-01', 'UMich-02b', 'vitafiber',
                   'vitagos', 'wako', 'yacontrol']


ordered_media = MONOSACCHARIDES + DISACCHARIDES + OLIGOSACCHARIDES + POLYSACCHARIDES

VITRO_MEDIA_COLORS = {'glucose': 'red', 'lactose': 'blue', 'vitafiber':'green'} \
                | {medium:KELLY_COLORS[m%len(KELLY_COLORS)] for m, medium in enumerate(ordered_media)  if medium not in ['glucose', 'lactose', 'vitafiber']}


medium_labels = {medium:medium for medium in ordered_media}
medium_labels['iron'] = 'gluc. + iron'


gene_coords_map = {}
gene_description = {}
gene_starts, gene_stops = [], []
gene_lst = []
with open(f'{data_dir}/reference_genome/BtVPI.ptt', 'r') as f:
    for _ in range(4):
        header = next(f)
    for line in f:
        line_items = line.strip('\n').split('\t')
        loc_str, strand = line_items[0], line_items[1]
        gene, description = line_items[5], line_items[-1]

        start, stop = [int(e) for e in loc_str.split('..')]
        gene_coords_map[gene] = (start, stop, strand)
        gene_description[gene] = description
        gene_starts.append(start)
        gene_stops.append(stop)
        gene_lst.append(gene)
gene_starts, gene_stops = np.array(gene_starts), np.array(gene_stops)
genes = np.array(gene_lst)

def find_gene_from_position(position):
    jc_start = position >= gene_starts
    jc_stop = position <= gene_stops

    if (jc_start * jc_stop).sum() > 0:
        return genes[ jc_start * jc_stop ]
    else: # intergenic
        if np.any(~jc_start) and np.any(~jc_stop):
            left_gene = genes[~jc_stop][-1]
            right_gene = genes[~jc_start][0]
        elif np.any(~jc_start):
            right_gene = genes[~jc_start][0]
            left_gene = genes[-1]
        elif np.any(~jc_stop):
            right_gene = genes[~jc_stop][-1]
            left_gene = genes[0]

        return [f'{left_gene}-{right_gene}']

##########################################
### BARCODE FREQ CALCULATIONS  ####
##########################################

# def calc_freqs(read_array):
#     if read_array.ndim > 1:
#         return np.einsum('ij, i->ij', read_array, read_array.sum(axis=1)**-1.)
#     else:
#         return read_array / read_array.sum()

def maxmin_freqs(freqs0, depth0, freqs1, depth1):
    if type(freqs0) != np.ndarray:
        freqs0 = np.array(freqs0)
        freqs1 = np.array(freqs1)

    overD0 = np.full(freqs0.shape[-1], 1 / depth0)
    overD1 = np.full(freqs1.shape[-1], 1 / depth1)

    # max_f0 = np.max([freqs0, overD0], axis=0)
    # max_f0[freqs0 == 0] = 0
    # min_f0 = np.min([freqs1, overD0], axis=0)
    # maxmin_f0 = np.max([max_f0, min_f0], axis=0)

    # max_f1 = np.max([freqs1, overD1], axis=0)
    # max_f1[freqs1 == 0] = 0
    # min_f1 = np.min([freqs0, overD1], axis=0)
    # maxmin_f1 = np.max([max_f1, min_f1], axis=0)

    min_f0 = np.min([freqs1, overD0], axis=0)
    maxmin_f0 = np.max([freqs0, min_f0], axis=0)

    min_f1 = np.min([freqs0, overD1], axis=0)
    maxmin_f1 = np.max([freqs1, min_f1], axis=0)

    return maxmin_f0, maxmin_f1

def get_freqs(expt, mouse, day):
    row_id = vivo_row_ids[(expt, mouse, day)]
    freqs = freq_array[row_id]
    depth = read_array[row_id].sum()
    effective_depth = Deff_array[row_id]
    return freqs, depth

def cage_avg_freqs(expt, mice, day):
    weighted_read_array = np.zeros(vivo_array.shape[-1])
    weighted_depth = 0

    for mouse in mice:
        if (expt, mouse, day) in library_array_map:
            mouse_days, mouse_reads, mouse_depths = get_mouse_timecourse(expt, mouse, specific_timepoints=[day])
            weighted_read_array += mouse_reads[0] 
            weighted_depth += mouse_depths[0]
    weighted_freq_array  = weighted_read_array/weighted_depth
    return weighted_freq_array, weighted_depth

##########################################
### MULLER PLOTS ####
##########################################
highlight_barcode_hatches = {'GCCTTATAAATCTGGCTCTT': '\\\\\\\\', 'TGCTTCCGGCTTGGAAACCG': '////'}

def find_large_barcodes(expt, mice, max_cutoff=1e-2, final_cutoff=1, max_timepoint=100):
    all_large_indices = set()
    for mouse in mice:
        
        # mouse_rows = library_meta[expt][mouse][1]
        # mouse_depths = Deff_array[mouse_rows]
        # # max_freqs = np.max(freq_array[mouse_rows][mouse_depths**-1. < max_cutoff*1/10], axis=0) #exclude day 0
        # # max_freqs = np.max(freq_array[mouse_rows][mouse_depths**-1. < max_cutoff], axis=0) #exclude day 0
        # max_freqs = np.max(freq_array[mouse_rows], axis=0) #exclude day 0


        # final_timepoint_row = mouse_rows[-1]
        # final_freqs = freq_array[final_timepoint_row]

        mouse_days, mouse_reads, mouse_depths = get_mouse_timecourse(expt, mouse)
        mouse_freqs = calc_freqs(mouse_reads, mouse_depths)
        max_freqs = np.max(mouse_freqs[mouse_days < max_timepoint], axis=0) #exclude day 0
        final_freqs = mouse_freqs[-1]

        large_indices = np.where( (max_freqs > max_cutoff) + (final_freqs > final_cutoff) > 0)[0]
        all_large_indices.update( large_indices )

    all_large_indices = np.array(list(all_large_indices))
    return all_large_indices

def order_barcodes_by_pool(large_barcodes, barcode_pool_assignments,  ordered_pool_color_tuples, num_colors_in_pool=18, cg_at_end=True, cg_all_low_freqs=False):
    ordered_indices = []
    ordered_colors = []

    cg_lst = []
    cg_colors = []

    for pool, pool_colormap in ordered_pool_color_tuples:
        pool_barcodes = barcode_pool_assignments[pool][0]
        pool_cmap = mpl.colormaps[pool_colormap]
        color_run = list(iter(pool_cmap(np.linspace(0.5, 1.0, num_colors_in_pool))))
        color_run = color_run[0::3] + color_run[1::3] + color_run[2::3] # scramble adjacent colors


        small_barcode_indices = []
        c = 0
        for barcode in pool_barcodes:
            if [barcode] in ordered_indices:
                continue
            if barcode in large_barcodes:
                ordered_indices.append( [barcode] )
                ordered_colors.append(color_run[c % num_colors_in_pool])
                c += 1
            else:
                small_barcode_indices.append(barcode)

        
        if cg_all_low_freqs: #single cg_lst
            cg_lst.extend( small_barcode_indices )
        elif cg_at_end:
            cg_lst.append( small_barcode_indices )
            cg_colors.append( pool_cmap(0.35) )
        else:
            ordered_indices.append( small_barcode_indices )
            ordered_colors.append( pool_cmap(0.35) )

    if cg_all_low_freqs:
        ordered_indices.append(cg_lst)
        ordered_colors.append('lightgrey')
    elif cg_at_end:
        ordered_indices.extend(cg_lst)
        ordered_colors.extend(cg_colors)

    return ordered_indices, ordered_colors 

# def make_muller_freqs(expt, mouse, sorted_indices, exclude_lowdepth=1000):
#     days = library_meta[expt][mouse][0]
#     rows = library_meta[expt][mouse][1]

#     included_days = []
#     freqs = []
    
#     for day, row in zip(days, rows):
#         day_freqs = []
#         mouse_freqs = freq_array[row]
#         mouse_depth = read_array[row].sum()

#         mouse_Deff = Deff_array[row]
        
#         if mouse_Deff < exclude_lowdepth: #if above threshold
#             continue
        
#         included_days.append(day)
#         for lineage_indices in sorted_indices:
#             day_freqs.append( mouse_freqs[lineage_indices].sum() ) 
#         day_freqs.append( 1 - np.sum(day_freqs) ) #leftover

#         freqs.append(day_freqs)

#     return np.array(included_days), np.array(freqs)

def make_muller_freqs(expt, mouse, sorted_indices, exclude_lowdepth=1000, include_reseq=True, include_pseudo_derepped=True, min_depth=10**3):
    days, mouse_reads, mouse_depths = get_mouse_timecourse(expt, mouse,
                                                           include_reseq=include_reseq, 
                                                           include_pseudo_derepped=include_pseudo_derepped,
                                                           min_depth=min_depth)

    mouse_freqs = calc_freqs(mouse_reads, mouse_depths)

    included_days = []
    muller_freqs = []
    
    for day, freqs, depth in zip(days,  mouse_freqs, mouse_depths):
        day_freqs = []
        
        if depth < exclude_lowdepth: #if above threshold
            continue
        
        included_days.append(day)
        for lineage_indices in sorted_indices:
            day_freqs.append( freqs[lineage_indices].sum() ) 
        day_freqs.append( 1 - np.sum(day_freqs) ) #leftover
        muller_freqs.append(day_freqs)


    # print(included_days)
    return np.array(included_days), np.array(muller_freqs)

def make_vitro_muller_freqs(passages, freqs, sorted_indices, exclude_lowdepth=1000):
    included_passages = []
    muller_freqs = []
    for passage, passage_freqs in zip(passages, freqs):
        stacked_freqs = []
      
        included_passages.append(passage)
        for lineage_indices in sorted_indices:
            stacked_freqs.append( passage_freqs[lineage_indices].sum() ) 
        stacked_freqs.append( 1 - np.sum(stacked_freqs) ) #leftover

        muller_freqs.append(stacked_freqs)

    return np.array(included_passages), np.array(muller_freqs)

def muller_plot(ax, times, bc_indices, freqs, colors, hatch_dict={}):
    """ freqs has dimensions of (time, bc freq).
     times and freqs.shape[0] should have same dimension. """
    cum_freqs = np.cumsum(freqs, axis=1)

    # ax.fill_between(times, cum_freqs[:, i], cum_freqs[:, i+1], facecolor=colors[i + 1])
    
    ## first lineage
    try:
        hatch = hatch_dict.get(barcodes[bc_indices[0][0]], None)
    except:
        hatch = None
    ax.fill_between(times, 0, cum_freqs[:, 0], facecolor=colors[0], lw=0, rasterized=True, hatch=hatch) #first lineage
    for i in range(1, cum_freqs.shape[1]-1):
        try:
            hatch = hatch_dict.get(barcodes[bc_indices[i][0]], None)
        except:
            hatch = None
        ax.fill_between(times, cum_freqs[:, i-1], cum_freqs[:, i], facecolor=colors[i], lw=0, rasterized=True, hatch=hatch)

    ax.fill_between(times, cum_freqs[:, -2], cum_freqs[:, -1], color='lightgrey', lw=0, rasterized=True)
    # ax.plot(times, cum_freqs[:, -6], color='black', lw=2)

##########################################
### DIVERSITY STATISTICS (ENTROPY, NUM. BARCODES DETECTED, MEAN-FITNESS) ####
##########################################

def coarse_grain(sorted_freqs, max_groups=3, min_freq=10**-2, recursive=False):
    groupings = [[] for i in range(max_groups)]
    current_freqs = [sorted_freqs[group].sum() for group in groupings]

    for i, f in enumerate(sorted_freqs):
        z = np.argmin(current_freqs)
        groupings[z].append(i)
        current_freqs = [sorted_freqs[group].sum() for group in groupings]

    if np.min(current_freqs) > min_freq:
        return groupings, np.array(current_freqs)

    else:
        if recursive:
            return coarse_grain(sorted_freqs, max_groups=len(groupings)-1, min_freq=min_freq)
        else:
            return groupings, np.array(current_freqs)

def high_frequency_expectation(sampled_days, freqs, high_frequency_indices, Deff_array, Ntau=10**5, min_day=0):
    low_frequency_indices = np.array([i not in high_frequency_indices for i in np.arange(freqs.shape[1])])
    high_frequency_sum = freqs[:, high_frequency_indices].sum(axis=1)

    ## convert high_frequency_sum to an expected mean fitness over time
    int_Xbar = -np.log((1-high_frequency_sum) / (1-high_frequency_sum[0]))
    Xbar_in_interval = np.diff(int_Xbar) / np.diff(sampled_days) # assume Xbar is roughly constant in a sampled interval (should be true for small intervals)

    Xbar_lst = []
    for day in range(min_day, np.max(sampled_days)):
        Xbar_lst.append( Xbar_in_interval[ np.where(sampled_days <= day)[0][-1] ] )

    sampled_array = [freqs[0]]
    sim_low_freqs = freqs[0, low_frequency_indices]

    integrated_Xbar = 1
    for i, day in enumerate(range(min_day+1, np.max(sampled_days)+1)):
        Xbar = Xbar_lst[i]

        sim_low_freqs =  sim.rnd.poisson(sim_low_freqs * np.exp(-Xbar) * Ntau) / Ntau 
        integrated_Xbar *= np.exp(-Xbar)
        if day in sampled_days:
            day_index = np.where(sampled_days == day)[0][0]

            expected_array = np.copy(freqs[day_index])
            expected_array[low_frequency_indices] = sim_low_freqs * (1-expected_array[high_frequency_indices].sum()) / sim_low_freqs.sum()

            sampled_reads = sim.rnd.poisson(expected_array * Deff_array[ day_index ]) 
            sampled_freqs = sampled_reads / sampled_reads.sum()

            # sampled_reads = sim.rnd.poisson(sampled_freqs * Deff_array[ day_index ]) 
            # sampled_freqs = sampled_reads / sampled_reads.sum()

            sampled_array.append(sampled_freqs)
    return np.array(sampled_array)

def calc_median_lfc(freq_array, Deff_array, barcode_groups): #day0_freqs = ref_freqs
    ref_freqs, D0 = freq_array[0], Deff_array[0]

    median_lfc_lst = []
    for freqs_t, Dt in zip(freq_array[1:], Deff_array[1:]):
        median_lfcs = []


        for group_indices in barcode_groups:
            f1_group = ref_freqs[group_indices]
            f2_group = freqs_t[group_indices]
            if np.percentile(f2_group, 50) == 0: #if most barcodes in group are unmeasured, exclude
                continue 
                    
            f1_maxmin, f2_maxmin = maxmin_freqs(f1_group, D0, f2_group, Dt)
            lfc = np.log( f2_maxmin / f1_maxmin )
            median_lfcs.append( [np.median(lfc), lfc] )


            # lfcs_in_group = lfc[group_indices]
            # noise_max = np.log( 1 / (Dt * np.min(ref_freqs[group_indices])) )  
            
            # median_lfc = np.median( lfcs_in_group )
            # if median_lfc - noise_max > 0: # if at least half of barcodes in group are measured --> THIS WILL OVERESTIMATE LFC (UNDERESTIMATE MEAN FITNESS)
            #     median_lfcs.append( median_lfc )
        median_lfc_lst.append( median_lfcs )

    return median_lfc_lst

def calc_entropy(freq_array, min_freq=1e-4):
    entropy_lst = []
    for freqs in freq_array:
        where_large = freqs > min_freq
        if where_large.sum() == 0:
            entropy_lst.append(0)
        else:
            large_freqs = freqs[where_large] / freqs[where_large].sum()
            entropy = scipy.stats.entropy(large_freqs)
            entropy_lst.append(entropy)

    return np.array(entropy_lst)

def calc_measured_frequencies(true_frequencies, depths):
    measured_frequencies = []
    for true_freqs, depth in zip(true_frequencies, depths):
        measured_counts = sim.rnd.poisson(depth * true_freqs)
        measured_frequencies.append( measured_counts / np.sum(measured_counts) )
    return np.array( measured_frequencies )

def estimate_num_barcodes_above_cutoff(expt, mouse, cutoffs, min_depth=10**3, bc_dict=None):
    mouse_days, mouse_reads, mouse_depths = get_mouse_timecourse(expt, mouse, min_depth=min_depth)
    mouse_floors = mouse_depths**-1.
    freq_array = calc_freqs(mouse_reads, mouse_depths)
    day0_freqs = freq_array[0]

    if type(cutoffs) != list and type(cutoffs) != np.ndarray:
        cutoffs = [cutoffs]

    valid_days, n_barcodes_by_cutoff = [], []
    for cutoff in cutoffs:
        min_depth = np.max([min_depth, 3/cutoff])
        valid = (mouse_floors < np.min([cutoff, min_depth**-1.]))
        freqs = freq_array[valid]
        n_barcodes_above_cutoff = (freqs > cutoff).sum(axis=1)
        valid_days.append( mouse_days[valid] )
        n_barcodes_by_cutoff.append( n_barcodes_above_cutoff )

    return valid_days, n_barcodes_by_cutoff

def estimate_num_barcodes_above_cutoff_simulated(expt, mouse, cutoffs, Ntau=10**6, min_depth=10**3):
    mouse_days, mouse_reads, mouse_depths = get_mouse_timecourse(expt, mouse, min_depth=min_depth)
    mouse_floors = mouse_depths**-1.
    freq_array = calc_freqs(mouse_reads, mouse_depths)
    day0_freqs = freq_array[0]
    
    neutral_sim_freqs = sim.neutral_sim(day0_freqs, Ntau, mouse_days, mouse_floors**-1.)

    if type(cutoffs) != list and type(cutoffs) != np.ndarray:
        cutoffs = [cutoffs]
        
    valid_days, n_barcodes_by_cutoff = [], []
    for cutoff in cutoffs:
        valid = (mouse_floors < np.min([cutoff, min_depth**-1.])) 
        freqs = neutral_sim_freqs[valid]
        n_barcodes_above_cutoff = (freqs > cutoff).sum(axis=1)

        valid_days.append( mouse_days[valid] )
        n_barcodes_by_cutoff.append( n_barcodes_above_cutoff )

    return valid_days, n_barcodes_by_cutoff


##########################################
#### TRANSMISSION MEASUREMENTS ####
##########################################


def conditioning(donor_freqs, recip_freqs0, donor_min=0, recip_max=0, pool_assignment_bool=None, donor_freq_range=(0,1)):
    valid_bool = (donor_freqs >= donor_min) * (recip_freqs0 <= recip_max) * (donor_freqs >= donor_freq_range[0]) * (donor_freqs < donor_freq_range[1])
    if np.any(pool_assignment_bool) != None:
        valid_bool = valid_bool * pool_assignment_bool
    return valid_bool

# functions for prob. detect-based inference of transmission
def calc_p_detected(donor_freqs, recip_freqs, recip_floor=0, binspace=np.logspace(-5,0,51), pseudocount=0):
    density = []
    errs = []
    n_barcodes = []

    recip_floor = np.max([1e-8, recip_floor])
    for b, freq_bin in enumerate(binspace[:-1]):
        where_in_bin = (donor_freqs >= freq_bin) * (donor_freqs < binspace[b+1])
        where_nonzero = (recip_freqs[where_in_bin] > recip_floor)


        if where_in_bin.sum() >= 1:
            n = where_in_bin.sum()
            p = where_nonzero.sum() / n
            if p == 0:
                p = pseudocount/n
            density.append( p)
            n_barcodes.append( where_in_bin.sum() )
            if p*(1-p) > 0:
                errs.append( np.sqrt(p*(1-p)/n ) )
            else:
                errs.append( np.sqrt(1/(2*n)*(1-1/(2*n))/(2*n) ) )
        else:
            density.append(np.nan)
            errs.append( np.nan)
            n_barcodes.append( where_in_bin.sum() )
    return np.array(density), np.array(errs), 1/2*(binspace[:-1] + binspace[1:]), np.array(n_barcodes)


def migration_inference_by_pdetected(donor_data, recip_data0, recip_data1, valid_bool, recip_floor=0, binspace=np.logspace(-5,0,51), pseudocount=0):
    donor_freqs, donor_depth = donor_data
    recip_freqs0, recip_depth0 = recip_data0
    recip_freqs1, recip_depth1 = recip_data1
    
    density, errs, bins, n_barcodes_per_bin = calc_p_detected(donor_freqs[valid_bool], recip_freqs1[valid_bool],
                                          recip_floor=recip_floor, binspace=binspace, pseudocount=pseudocount)
    # if np.all(recip_freqs1[valid_bool] > 0):
    #     return 0, 0, density, errs, bins
    notnan = ~np.isnan(density) * (density > 0)

    if np.sum(recip_freqs1[valid_bool]) == 0: #no detected barcodes --> find m such that prob of zero measured barcodes == 1/2
        m = np.log(2) / np.sum(donor_freqs[valid_bool]*recip_depth1)
        print('no detected barcodes, m=',  m)
        return m, 0, density, errs, bins, n_barcodes_per_bin

    if notnan.sum() < 2:
        return np.nan, np.nan, density, errs, bins, n_barcodes_per_bin

    def detection_neg_loglikelihood(Dm, f_d, f_r):
        f_present = (f_r > recip_floor).astype(int)
        term1 = (-f_d * Dm)*(1-f_present)
        term2 = np.log(1-np.exp(-f_d * Dm))*f_present
        return -(term1+term2).sum()

    def detection_neg_ll_jac(Dm, f_d, f_r):
        f_present = (f_r > recip_floor).astype(int)
        numerator = f_d**2 * f_present
        denominator = 2*(np.cosh(Dm * f_d)-1)
        return (numerator/denominator).sum()


    res = scipy.optimize.minimize(detection_neg_loglikelihood, x0 = 1, args=((donor_freqs[valid_bool], recip_freqs1[valid_bool])))
    m = res.x[0]/recip_depth1
    uncertainty = detection_neg_ll_jac(res.x[0], donor_freqs[valid_bool], recip_freqs1[valid_bool]) **-0.5 / recip_depth1

    return m, uncertainty, density, errs, bins, n_barcodes_per_bin

# functions for weighted average rate of transmission
def coarse_grain(sorted_freqs, max_groups=3, min_freq=10**-2):
    groupings = [[] for i in range(max_groups)]
    current_freqs = [sorted_freqs[group].sum() for group in groupings]

    for i, f in enumerate(sorted_freqs):
        z = np.argmin(current_freqs)
        groupings[z].append(i)
        current_freqs = [sorted_freqs[group].sum() for group in groupings]

    return groupings, np.array(current_freqs)

def migration_inference_by_ratio(donor_data, recip_data0, recip_data1, valid_bool, recip_floor=0, max_groups=2, min_freq=10**-2):
    donor_freqs, donor_depth = donor_data
    recip_freqs0, recip_depth0 = recip_data0
    recip_freqs1, recip_depth1 = recip_data1

    donor_valid = np.copy(donor_freqs[valid_bool])
    recip_valid = np.copy(recip_freqs1[valid_bool])
    recip_valid[recip_valid < recip_floor] = 0
    sorting = np.argsort(donor_valid)

    cg_donor, cg_recip = [], []
    for max_group in range(2, max_groups+1, 1):
        donor_coarse_graining = coarse_grain(donor_valid[sorting], max_groups=max_group, min_freq=min_freq)
        cg_groups, cg_donor_freqs = donor_coarse_graining

        cg_recipient_freqs1 = np.array([recip_valid[sorting][cg_group].sum() for cg_group in cg_groups])
        coarse_grained_ratios = cg_recipient_freqs1 / cg_donor_freqs

        cg_donor.extend(list(cg_donor_freqs))
        cg_recip.extend(list(cg_recipient_freqs1))

        if max_group == 2:
            m = np.median(coarse_grained_ratios)

    return m, (donor_valid, np.array(cg_donor)), (recip_valid, np.array(cg_recip)), coarse_grained_ratios

def p_transmit(f, m):
    return 1 - np.exp(-m*f)

def find_consecutive_timepoints(expt, donor_mice, recipient_mouse, min_day=11, max_dt=2, max_day=55, min_depth=10**3):
    consecutive_sampled_days = set()
    all_donor_days = [] 
    for donor in donor_mice:
        donor_days, reads, depths = get_mouse_timecourse(expt, donor, min_depth=min_depth)
        all_donor_days.extend(donor_days)
    all_donor_days = np.unique(all_donor_days)
    recip_days, reads, depths = get_mouse_timecourse(expt, recipient_mouse, min_depth=min_depth,
                                                      include_pseudo_derepped=True)

    for day in range(min_day, max_day+1): # first timepoint
        if day in all_donor_days:
            for dt in range(1,max_dt+1): # second timepoint = day + dt
                if day in recip_days and day+dt in recip_days:
                    consecutive_sampled_days.add( (day, day+dt) )
    return sorted(consecutive_sampled_days, key=lambda x: x[0])

def measure_transmission_in_interval(expt, recipient_mouse, donor_mice, t0, t1, 
                                     pool_assignment_bool=None, coarse_grain_num_groups=2, min_barcodes=10,
                                     rescale_migration = 1, donor_freq_range=(0, 1), detect_threshold=0, include_runs=(True,True)):
    
    donor_freqs = []
    donor_floors = []
    try:
        for donor in donor_mice:
            try:
                donor_days, reads, depths = get_mouse_timecourse(expt, donor, min_depth=10**3, specific_timepoints=[t0], include_reseq=True, include_pseudo_derepped=True)
            except:
                continue
            donor_freqs.append( calc_freqs(reads, depths)[0] )
            donor_floors.append( 1 / depths[0] )
        donor_freqs = np.mean(donor_freqs, axis=0)
        donor_floor = np.min(donor_floors)

        
        (t0, t1), recip_reads, recip_depths = get_mouse_timecourse(expt, recipient_mouse, min_depth=10**3, specific_timepoints=[t0, t1], 
                                                                include_reseq=include_runs[0], include_pseudo_derepped=include_runs[1])
    except:
        print('Error retrieving barcode frequency data')
        return None
    
    recip_freqs_t0, recip_freqs_t1 = calc_freqs(recip_reads, recip_depths)
    recip_floor_t0, recip_floor_t1 =  1 / recip_depths

    donor_data = (donor_freqs, donor_floor**-1.)
    recip_data0 = (recip_freqs_t0, recip_floor_t0**-1.)
    recip_data1 = (recip_freqs_t1, recip_floor_t1**-1.)

    # find barcodes that are valid for inference
    donor_min = 2*donor_floor
    valid_bool = conditioning(donor_freqs, recip_freqs_t0, donor_min=donor_min, recip_max=0, pool_assignment_bool=pool_assignment_bool, donor_freq_range=donor_freq_range)
    if valid_bool.sum() < min_barcodes:
        print(f'Not enough barcodes for {recipient_mouse} at {t0} to {t1}')
        return None


    # print(valid_bool.sum(), donor_data, recip_data0, recip_data1)
    pdetection_inference = migration_inference_by_pdetected(donor_data, recip_data0, recip_data1, valid_bool, recip_floor=detect_threshold*recip_floor_t1)
    m_detected, m_detected_err, density, errs, bins, n_barcodes_per_bin = pdetection_inference

    ratio_inference = migration_inference_by_ratio(donor_data, recip_data0, recip_data1, valid_bool, max_groups=coarse_grain_num_groups, recip_floor=detect_threshold*recip_floor_t1)
    m_ratio, (donor_valid, donor_cg), (recip_valid, recip_cg), ratios = ratio_inference
    m_ratio_err = np.abs(np.diff(ratios)[0])/2

    output_dict = {}
    output_dict['freq floors'] = (donor_floor, recip_floor_t0, recip_floor_t1)
    output_dict['detected inference'] = (m_detected * rescale_migration, m_detected_err * rescale_migration)
    output_dict['ratio inference'] = (m_ratio * rescale_migration, m_ratio_err * rescale_migration)
    output_dict['detected raw data'] = (bins, density, errs, n_barcodes_per_bin)
    output_dict['ratio raw data'] = (donor_valid, recip_valid, donor_cg, recip_cg)

    return output_dict

##########################################
#### ENGRAFTMENT TRACKING ####
##########################################

def calc_interpolated_freqs(known_trajectory, remove_zeros=True, Deff_array=[], start_day=None):
    """ Assumes sampled frequencies never zero! """
    days, freqs = known_trajectory
    days, freqs = np.array(days), np.array(freqs)

    interpolated_days, interpolated_freqs = [], []

    if remove_zeros: #otherwise log-interpolation fails
        freqs[freqs == 0] = 1/Deff_array[freqs == 0]

    if not start_day:
        start_day = np.min(days)
    for day in range(start_day, np.max(days)+1):
        if day in days:
            interpolated_days.append(day)
            freq = freqs[days == day][0]
            interpolated_freqs.append(freq)
        else:
            nearest_day_before = np.max(days[days < day]) #nearest sampled day before
            nearest_day_after = np.min(days[days > day])

            freq_before = freqs[days == nearest_day_before][0]
            freq_after = freqs[days == nearest_day_after][0]

            log_slope = ( np.log(freq_after) - np.log(freq_before) ) / (nearest_day_after - nearest_day_before)
            log_interp_freq = np.log(freq_before) + log_slope*(day - nearest_day_before)

            interpolated_days.append(day)
            interpolated_freqs.append( np.exp(log_interp_freq) )
    
    return np.array(interpolated_days), np.array(interpolated_freqs)
      
    
# def trajectory_inference(donor_trajectory, recip_init, donor_transmission, recip_transmission, no_engraftment=False):
#     donor_days, donor_freqs = donor_trajectory
#     donor_days, donor_freqs = np.array(donor_days), np.array(donor_freqs)
#     recip_init = np.array(recip_init)
#     recip_transmission  = np.array(recip_transmission)


#     assert np.all(np.diff(donor_days) == 1)

#     recip_freqs = np.zeros((len(recip_init), len(donor_days)))
#     recip_freqs[:, 0] = recip_init

#     for i, day in enumerate(donor_days[1:]):
#         mean_freq = (donor_freqs[i] + np.sum(recip_freqs[:, i])) / (len(recip_init) + 1)
#         effective_fitness = (donor_freqs[i+1] - donor_transmission * mean_freq) / ((1- donor_transmission)*donor_freqs[i])
#         if no_engraftment:
#             effective_fitness = 0

#         # print(effective_fitness)
#         recip_freqs[:, i+1] = (1 - recip_transmission) * effective_fitness * recip_freqs[:, i] + recip_transmission * mean_freq

#     return donor_days, recip_freqs

def recipient_trajectory_model(donor_trajectories, recip_init, donor_transmission, recip_transmission, no_engraftment=False):
    # donor_trajectories is a list of donor trajectories = [(donor1_days, donor1_freqs), (donor2_days, donor2_freqs), ...]
    # requires donor_trajectories interpolated over all days in interval
    # this model assumes that the donors behave essentially identically, and we can ignore drift

    donor_days = donor_trajectories[0][0]
    print(len(donor_trajectories))    
    assert np.all(np.diff(donor_days) == 1)
    for other_donor_days, other_donor_freqs in donor_trajectories[1:]:
        assert np.all(donor_days == other_donor_days)
    donor_avg = np.mean([freqs for days, freqs in donor_trajectories], axis=0)

    recip_init = np.array(recip_init)
    recip_transmission  = np.array(recip_transmission)
    
    recip_freqs = np.zeros((len(recip_init), len(donor_days)))
    recip_freqs[:, 0] = recip_init

    for i, day in enumerate(donor_days[1:]):
        mean_freq = (donor_avg[i]*len(donor_trajectories) + np.sum(recip_freqs[:, i])) / (len(recip_init) + len(donor_trajectories))
        effective_fitness = (donor_avg[i+1] - donor_transmission * mean_freq) / ((1- donor_transmission)*donor_avg[i])
        if no_engraftment:
            effective_fitness = 0

        # print(effective_fitness)
        recip_freqs[:, i+1] = (1 - recip_transmission) * effective_fitness * recip_freqs[:, i] + recip_transmission * mean_freq

    return donor_days, recip_freqs

def plot_barcode_trajectories(ax, barcode, expt, donor_mice, recip_mice, transmission_dict, color_dict, init_day,
                               plot_other_donors=False, save_seq=False, recip_theory_colors=None):
    barcode_index = np.where(barcodes == barcode)[0][0]

    # donor_trajectories = {}
    # for donor_mouse in donor_mice:
    #     days, reads, depths = get_mouse_timecourse(expt, donor_mouse, min_depth=10**4)
    #     freqs = calc_freqs(reads, depths)
    #     donor_trajectories[donor_mouse] = [days, freqs[:, barcode_index], depths]
    # donor_interpolated_trajectories = {donor_mouse:[*calc_interpolated_freqs((days, freqs), remove_zeros=True, Deff_array=Deff)] for donor_mouse, (days, freqs, Deff) in donor_trajectories.items()}
    # donor_init_freqs = sorted([(donor_mouse, freqs[days == init_day][0]) for donor_mouse, [days, freqs] in donor_interpolated_trajectories.items()], key = lambda x: x[1], reverse=True)
    # reference_donor = donor_init_freqs[0][0] #mouse with highest freq at init day
    # ref_donor_days, reference_freqs = donor_interpolated_trajectories[ reference_donor ]
    
    donor_trajectories = []
    donor_interpolated_trajectories = []
    for donor_mouse in donor_mice:
        days, reads, depths = get_mouse_timecourse(expt, donor_mouse, min_depth=10**4)
        freqs = calc_freqs(reads, depths)[:, barcode_index]
        donor_trajectories.append([days, freqs, depths])
        donor_interpolated_trajectories.append( calc_interpolated_freqs((days, freqs), remove_zeros=True, Deff_array=depths, start_day=init_day) )

    donor_transmission = transmission_dict[donor_mice[0]]
    
    recip_init = []
    recip_transmission = []
    # if len(donor_init_freqs) > 1:
    #     for donor, init_freq in donor_init_freqs[:1]:
    #         recip_init.append(init_freq)
    #         recip_transmission.append(transmission_dict[donor])

    recip_init.extend( [0]*len(recip_mice) ) #assume 0 freq in recipient
    recip_transmission.extend( [transmission_dict[m] for m in recip_mice] )

    recip_days, recip_freqs = recipient_trajectory_model(donor_interpolated_trajectories, recip_init, donor_transmission, recip_transmission)
    recip_days, recip_freqs_transient = recipient_trajectory_model(donor_interpolated_trajectories, recip_init, donor_transmission, recip_transmission, no_engraftment=True)

    # ax.plot(donor_interpolated_trajectories[0][0], np.mean([d[1] for d in donor_interpolated_trajectories], axis=0) + 1e-7, color='green', alpha=1, lw=3)  
    
    # recip_days, recip_freqs = recipient_trajectory_model((ref_donor_days[ref_donor_days >= init_day], reference_freqs[ref_donor_days >= init_day]), recip_init, donor_transmission, recip_transmission)
    # recip_days, recip_freqs_transient = recipient_trajectory_model((ref_donor_days[ref_donor_days >= init_day], reference_freqs[ref_donor_days >= init_day]), recip_init, donor_transmission, recip_transmission, no_engraftment=True)

    #### PLOT ###
    # ax.plot(donor_trajectories[reference_donor][0], donor_trajectories[reference_donor][1] + 1e-7, color=color_dict[reference_donor], alpha=1, lw=3)
    # if plot_other_donors:
    #     for (donor, init_freq) in donor_init_freqs[1:]:
    #         ax.plot(donor_trajectories[donor][0], donor_trajectories[donor][1] + 1e-7, color=color_dict[donor_init_freqs[1][0]], alpha=1, lw=3, zorder=0)

    # ax.plot(donor_trajectories[reference_donor][0], donor_trajectories[reference_donor][1] + 1e-7, color=color_dict[reference_donor], alpha=1, lw=3)
    for donor, (donor_days, donor_freqs, donor_depths) in zip(donor_mice, donor_trajectories):
        ax.plot(donor_days, donor_freqs + 1e-7, color=color_dict[donor], alpha=1, lw=3, zorder=0)
        # ax.plot(donor_trajectories[donor][0], donor_trajectories[donor][1] + 1e-7, color=color_dict[donor_init_freqs[1][0]], alpha=1, lw=3, zorder=0)



    if recip_theory_colors is None:
        recip_theory_colors = [('grey', 'black')]*len(recip_mice)
    #plot only one recipient theory curves (could do more, but it's a bit crowded)
    for recip_engrafted, recip_transient, colors in zip(recip_freqs[-1:], recip_freqs_transient[-1:], recip_theory_colors[-1:]):
        ax.plot( recip_days[1:], recip_transient[1:], color=colors[0], alpha=1, linestyle='dashed', lw=1.5)
        ax.plot( recip_days[1:], recip_engrafted[1:], color=colors[1], alpha=1, linestyle='dashed', lw=1.5)


    transient_expectation = {k:{day: recip_freqs_transient[1][m] for m, day in enumerate(recip_days)} for k in range(len(recip_mice))}
    # transient_expectation[0] = 0
    # recip_mice = [m for m in [4,5,6,7] if m != donor_mouse]
    reps = []
    for m, recip_mouse in enumerate(recip_mice):
        recip_days, recip_reads, recip_depths = get_mouse_timecourse(expt, recip_mouse, min_depth=10**4)
        recip_freqs = calc_freqs(recip_reads, recip_depths)[:, barcode_index]
        recip_floor = recip_depths**-1.
        mask = []
        for r, (day, floor) in enumerate(zip(recip_days, recip_floor)): #ignore timepoints that are likely to be zero / dominated by contamination
            if recip_freqs[r] > 0 and day >= init_day:
                mask.append(True)
            elif day in transient_expectation[m] and transient_expectation[m][day] > floor:
                mask.append(True)
            else:
                mask.append(False)

        ax.plot(recip_days[mask], recip_freqs[mask] + 1e-7, color=color_dict[recip_mouse], marker='.', markersize=5, lw=1.5, linestyle='solid')
        # ax.plot(recip_days, recip_freqs + 1e-7, color=color_dict[recip_mouse], marker='.', markersize=5, lw=1.5, linestyle='solid')

def plot_barcode_trajectories_and_save(ax, barcode, expt, donor_mice, recip_mice, transmission_dict, color_dict, init_day,
                               plot_other_donors=False, save_seq=False, recip_theory_colors=None):
    barcode_index = np.where(barcodes == barcode)[0][0]

    donor_days_and_rows = {donor_mouse:[*library_meta[expt][donor_mouse]] for donor_mouse in donor_mice}
    donor_trajectories = {donor_mouse:[days, freq_array[rows][:, barcode_index], Deff_array[rows]] for donor_mouse, [days, rows, cecum] in donor_days_and_rows.items()}

    donor_interpolated_trajectories = {donor_mouse:[*calc_interpolated_freqs((days, freqs), remove_zeros=True, Deff_array=Deff)] for donor_mouse, (days, freqs, Deff) in donor_trajectories.items()}
    donor_init_freqs = sorted([(donor_mouse,freqs[days == init_day]) for donor_mouse, [days, freqs] in donor_interpolated_trajectories.items()], key = lambda x: x[1], reverse=True)
    reference_donor = donor_init_freqs[0][0] #mouse with highest freq at init day
    donor_transmission = transmission_dict[reference_donor]

    ref_donor_days, reference_freqs = donor_interpolated_trajectories[ reference_donor ]
        
    recip_init = []
    recip_transmission = []
    if len(donor_init_freqs) > 1:
        for donor, init_freq in donor_init_freqs[1:]:
            recip_init.append(init_freq)
            recip_transmission.append(transmission_dict[donor])
    recip_init.extend( [0]*len(recip_mice) ) #assume 0 freq in recipient
    recip_transmission.extend( [transmission_dict[m] for m in recip_mice] )
      
    recip_days, recip_freqs = trajectory_inference((ref_donor_days[ref_donor_days >= init_day], reference_freqs[ref_donor_days >= init_day]), recip_init, donor_transmission, recip_transmission)
    recip_days, recip_freqs_transient = trajectory_inference((ref_donor_days[ref_donor_days >= init_day], reference_freqs[ref_donor_days >= init_day]), recip_init, donor_transmission, recip_transmission, no_engraftment=True)
    # print('Recip engrafted:', recip_freqs,)
    # print('Recip transient:', recip_freqs_transient)

    #### PLOT ###
    if save_seq != False:
        save_seq.savefig(f'{plot_dir}/E2_traj_presentation_v0.pdf', dpi=300, bbox_inches='tight', transparent=True)
    
    ax.plot(donor_trajectories[reference_donor][0], donor_trajectories[reference_donor][1] + 1e-7, color=color_dict[reference_donor], alpha=1, lw=3)
    if plot_other_donors:
        for (donor, init_freq) in donor_init_freqs[1:]:
            ax.plot(donor_trajectories[donor][0], donor_trajectories[donor][1] + 1e-7, color=color_dict[donor_init_freqs[1][0]], alpha=1, lw=3, zorder=0)
    if save_seq != False:
        save_seq.savefig(f'{plot_dir}/E2_traj_presentation_v1.pdf', dpi=300, bbox_inches='tight', transparent=True)


    ax.plot( recip_days[1:], recip_freqs_transient[1][1:], color='grey', alpha=1, linestyle='dashed', lw=1.5)
    if save_seq != False:
        save_seq.savefig(f'{plot_dir}/E2_traj_presentation_v2.pdf', dpi=300, bbox_inches='tight', transparent=True)

    ax.plot( recip_days[1:], recip_freqs[1][1:], color='black', alpha=1, linestyle='dashed', lw=1.5)
    if save_seq != False:
        save_seq.savefig(f'{plot_dir}/E2_traj_presentation_v3.pdf', dpi=300, bbox_inches='tight', transparent=True)


    transient_expectation = {k:{day: recip_freqs_transient[1][m] for m, day in enumerate(recip_days)} for k in range(len(recip_mice))}
    # transient_expectation[0] = 0

    # recip_mice = [m for m in [4,5,6,7] if m != donor_mouse]
    reps = []
    for m, recip_mouse in enumerate(recip_mice):
        recip_days, recip_rows = library_meta[expt][recip_mouse][:2]
        recip_reads = np.copy(read_array[recip_rows])
        recip_freqs = calc_freqs(recip_reads)
        # recip_freqs[recip_freqs == 0] = 1e-7

        recip_freqs = freq_array[recip_rows][:, barcode_index]
        recip_floor = Deff_array[recip_rows]**-1.

        mask = []
        for r, (day, floor) in enumerate(zip(recip_days, recip_floor)):
            if recip_freqs[r] > 0 and day >= init_day:
                mask.append(True)
            elif day in transient_expectation[m] and transient_expectation[m][day] > floor:
                mask.append(True)
            else:
                mask.append(False)

        ax.plot(recip_days[mask], recip_freqs[mask] + 1e-7, color=color_dict[recip_mouse], marker='.', markersize=5, lw=1.5, linestyle='solid')
        # ax.plot(recip_days, recip_freqs + 1e-7, color=color_dict[recip_mouse], marker='.', markersize=5, lw=1.5, linestyle='solid')
    
def calc_integrated_ratio(donor_freqs, recip_freqs, floor=10**-3):
        ratio = np.ma.masked_array(recip_freqs / donor_freqs, np.full(donor_freqs.shape[0], False))
        ratio[ ratio == 0 ] = floor
        # ratio[ np.isnan(ratio)] = floor
        ratio.mask[ ratio == 0] = True
        ratio.mask[ np.isnan(ratio) ] = True
        ratio.mask[ np.isinf(ratio)] = True
        donor_weights = np.ma.masked_array(donor_freqs, ratio.mask)
        donor_weights /= np.ma.sum(donor_weights)

        return np.ma.sum(ratio * donor_weights )
        # return np.ma.mean(ratio)
        # return np.exp( np.ma.sum( np.log(ratio)*donor_weights ) )

### in vitro

medium_to_well_map = {'glucose':[('p1_A1', 'V1'), ('p1_B1', 'V4'), ('p1_C1', 'V1'), ('p1_D1', 'V4')],
     'stachyose':[('p1_A2', 'V2'), ('p1_B2', 'V5'), ('p1_C2', 'V2'), ('p1_D2', 'V5')],
     'sucrose':[('p1_A3', 'V3'), ('p1_B3', 'V6'), ('p1_C3', 'V3'), ('p1_D3', 'V6')],
     'fructose':[('p1_A5', 'V1'), ('p1_B5', 'V4'), ('p1_C5', 'V1'), ('p1_D5', 'V4')],
     'maltose':[('p1_A6', 'V2'), ('p1_B6', 'V5'), ('p1_C6', 'V2'), ('p1_D6', 'V5')],
     'trehalose':[('p1_A7', 'V3'), ('p1_B7', 'V6'), ('p1_C7', 'V3'), ('p1_D7', 'V6')],
     'melibiose':[('p1_A9', 'V1'), ('p1_B9', 'V4'), ('p1_C9', 'V1'), ('p1_D9', 'V4')],
     'iron':[('p1_A10', 'V2'), ('p1_B10', 'V5'), ('p1_C10', 'V2'), ('p1_D10', 'V5')],
     'vitafiber':[('p1_A11', 'V3'), ('p1_B11', 'V6'), ('p1_C11', 'V3'), ('p1_D11', 'V6')],
     'raffinose':[('p1_E1', 'V1'), ('p1_F1', 'V4'), ('p1_G1', 'V1'), ('p1_H1', 'V4')],
     'lactose':[('p1_E2', 'V2'), ('p1_F2', 'V5'), ('p1_G2', 'V2'), ('p1_H2', 'V5')],
     'galactose':[('p1_E5', 'V1'), ('p1_F5', 'V4'), ('p1_G5', 'V1'), ('p1_H5', 'V4')],
     
     'UMich-01':[('p2_A1', 'V1'), ('p2_B1', 'V4'), ('p2_C1', 'V1'), ('p2_D1', 'V4')],
     'bioecolians':[('p2_A2', 'V2'), ('p2_B2', 'V5'), ('p2_C2', 'V2'), ('p2_D2', 'V5')],
     'prebiotin':[('p2_A3', 'V3'), ('p2_B3', 'V6'), ('p2_C3', 'V3'), ('p2_D3', 'V6')],
     'maltodextrin':[('p2_A5', 'V1'), ('p2_B5', 'V4'), ('p2_C5', 'V1'), ('p2_D5', 'V4')],
     'promitor':[('p2_A6', 'V2'), ('p2_B6', 'V5'), ('p2_C6', 'V2'), ('p2_D6', 'V5')],
     'vitagos':[('p2_A7', 'V3'), ('p2_B7', 'V6'), ('p2_C7', 'V3'), ('p2_D7', 'V6')],
     'precticx':[('p2_A9', 'V1'), ('p2_B9', 'V4'), ('p2_C9', 'V1'), ('p2_D9', 'V4')],
     'LC742':[('p2_A10', 'V2'), ('p2_B10', 'V5'), ('p2_C10', 'V2'), ('p2_D10', 'V5')],
     'avantafiber':[('p2_A11', 'V3'), ('p2_B11', 'V6'), ('p2_C11', 'V3'), ('p2_D11', 'V6')],

     'UMich-02b':[('p2_E1', 'V1'), ('p2_F1', 'V4'), ('p2_G1', 'V1'), ('p2_H1', 'V4')],
     'yacontrol':[('p2_E2', 'V2'), ('p2_F2', 'V5'), ('p2_G2', 'V2'), ('p2_H2', 'V5')],
     'fibersol':[('p2_E5', 'V1'), ('p2_F5', 'V4'), ('p2_G5', 'V1'), ('p2_H5', 'V4')],
     'cravingzgone':[('p2_E6', 'V2'), ('p2_F6', 'V5'), ('p2_G6', 'V2'), ('p2_H6', 'V5')],
     'bimuno':[('p2_E7', 'V3'), ('p2_F7', 'V6'), ('p2_G7', 'V3'), ('p2_H7', 'V6')],
     'sunfiber':[('p2_E9', 'V1'), ('p2_F9', 'V4'), ('p2_G9', 'V1'), ('p2_H9', 'V4')],
     'ISOT 160120':[('p2_E10', 'V2'), ('p2_F10', 'V5'), ('p2_G10', 'V2'), ('p2_H10', 'V5')],
     'wako':[('p2_E11', 'V3'), ('p2_F11', 'V6'), ('p2_G11', 'V3'), ('p2_H11', 'V6')]
     }
well_to_medium_map = {}
well_to_inoc_map = {}
for medium, wells in medium_to_well_map.items():
    for well in wells:
        well_to_medium_map[well[0]] = (medium, well[1])
        day0_lib = ('EV', well[1], 0)
        well_to_inoc_map[well[0]] = day0_lib #should be value in vitro_day0_map
        
